config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :items
  # get '/privacy', to: 'home#privacy'
  # get '/blog', to: 'home#blog'
  get '/contact', to: 'home#contact'
  get '/cv', to: 'home#cv'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_one_attached :header_image
  has_rich_text :wysiwyg
  
  def self.ransackable_attributes(auth_object = nil)
    ["archive", "content", "created_at", "description", "end", "id", "show_in_calendar", "show_on_blog", "show_on_portfolio", "start", "title", "updated_at"]
  end
  
  def self.ransackable_associations(auth_object = nil)
    []
  end

end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user

  Devise.omniauth_configs.keys.each do |provider|
    scope provider, ->{ where(provider: provider) }
  end

  def client
    send("#{provider}_client")
  end

  def expired?
    expires_at? && expires_at <= Time.zone.now
  end

  def access_token
    send("#{provider}_refresh_token!", super) if expired?
    super
  end


  def twitter_client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.secrets.twitter_app_id
      config.consumer_secret     = Rails.application.secrets.twitter_app_secret
      config.access_token        = access_token
      config.access_token_secret = access_token_secret
    end
  end

  def twitter_refresh_token!(token); end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable

  has_one_attached :avatar

  has_many :services
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  impersonates :user
  include Pundit::Authorization

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # show items that are show_on_portfolio = true
    @items = Item.where(show_on_portfolio: true).order(start: :asc).all
  end

  # def blog
  # end

  def contact
  end
  
  def cv
  end

  # def privacy
  # end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: %i[ show edit update destroy ]
  # GET /items or /items.json
  def index
    @q = Item.ransack(params[:q])
    @items = @q.result.paginate(page: params[:page], per_page: 10)
  end
  # GET /items/1 or /items/1.json
  def show
  end
  
  # GET /items/new
  def new
    @item = Item.new
  end
  
  # GET /items/1/edit
  def edit
  end
  
  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    
    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :header_image, :wysiwyg, :content, :show_on_portfolio, :show_on_blog, :show_in_calendar, :start, :end, :archive)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    before_action :set_service, except: [:failure]
    before_action :set_user, except: [:failure]

    attr_reader :service, :user

    def failure
      redirect_to root_path, alert: "Something went wrong"
    end

    def facebook
      handle_auth "Facebook"
    end

    def twitter
      handle_auth "Twitter"
    end

    def github
      handle_auth "Github"
    end

    private

    def handle_auth(kind)
      if service.present?
        service.update(service_attrs)
      else
        user.services.create(service_attrs)
      end

      if user_signed_in?
        flash[:notice] = "Your #{kind} account was connected."
        redirect_to edit_user_registration_path
      else
        sign_in_and_redirect user, event: :authentication
        set_flash_message :notice, :success, kind: kind
      end
    end

    def auth
      request.env['omniauth.auth']
    end

    def set_service
      @service = Service.where(provider: auth.provider, uid: auth.uid).first
    end

    def set_user
      if user_signed_in?
        @user = current_user
      elsif service.present?
        @user = service.user
      elsif User.where(email: auth.info.email).any?
        # 5. User is logged out and they login to a new account which doesn't match their old one
        flash[:alert] = "An account with this email already exists. Please sign in with that account before connecting your #{auth.provider.titleize} account."
        redirect_to new_user_session_path
      else
        @user = create_user
      end
    end

    def service_attrs
      expires_at = auth.credentials.expires_at.present? ? Time.at(auth.credentials.expires_at) : nil
      {
          provider: auth.provider,
          uid: auth.uid,
          expires_at: expires_at,
          access_token: auth.credentials.token,
          access_token_secret: auth.credentials.secret,
      }
    end

    def create_user
      User.create(
        email: auth.info.email,
        #name: auth.info.name,
        password: Devise.friendly_token[0,20]
      )
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def avatar_path(object, options = {})
    size = options[:size] || 180
    default_image = options[:default] || "mp"
    base_url =  "https://secure.gravatar.com/avatar"
    base_url_params = "?s=#{size}&d=#{default_image}"

    if object.respond_to?(:avatar) && object.avatar.attached? && object.avatar.variable?
      object.avatar.variant(resize_to_fill: [size, size])
    elsif object.respond_to?(:email) && object.email
      gravatar_id = Digest::MD5::hexdigest(object.email.downcase)
      "#{base_url}/#{gravatar_id}#{base_url_params}"
    else
      "#{base_url}/00000000000000000000000000000000#{base_url_params}"
    end
  end
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-primary"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/blog.html.haml
# %h1 Blog
# %p.lead Blog

app/views/home/contact.html.haml
%h1 CV of Service
%p.lead Use this for your Contact

app/views/home/cv.html.haml
%h1 CV of Service
%p.lead Use this for your CV

app/views/home/index.html.haml
.justify-content-center.align-items-center.min-vh-100
  %h1 Hi, I'm Bartosz!
  %p.lead
  You can go through this timeline to know me better or just click in menu to look at boring CV

// show records from item model
.container
  .row.justify-content-center.align-items-center.min-vh-100
    - @items.each do |item|
      .col-lg-8
        .card.mb-4
          .card-body
            .row.align-items-center
              .col-lg-4
                %img.img-fluid{:src => item.header_image, :alt => "Nice image here"}
              .col-lg-8
                %h5.card-title.text-right
                  = item.title
                %p.card-text.text-right
                  %small
                    - if item.end
                      = item.start.strftime("%Y-%m-%d")
                    %br
                    - if item.end
                      = item.end.strftime("%Y-%m-%d")
                %p.card-text.text-right
                  = item.description

app/views/home/privacy.html.haml
%h1 Privacy Policy
%p.lead Use this for your Privacy Policy

app/views/items/_form.html.haml
= form_with(model: item) do |form|
  - if item.errors.any?
    #error_explanation
      %h2
        = pluralize(item.errors.count, "error")
        prohibited this item from being saved:
      %ul
        - item.errors.full_messages.each do |message|
          %li= message
  .mb-3
    = form.label :title, class: 'form-label'
    = form.text_field :title, class: 'form-control'
  .mb-3
    = form.label :header_image, class: "form-label"
    = form.file_field :header_image, accept:'image/*'
    // show image if it exists
    = image_tag item.header_image if item.header_image.attached?
  .mb-3
    = form.label :description, class: 'form-label'
    = form.text_area :description, class: 'form-control'
  .mb-3
    = form.label :content, class: 'form-label'
    = form.rich_text_area :wysiwyg, class: 'form-control'
  .mb-3
    .form-check
      %label.form-check-label
        = form.check_box :show_on_portfolio, class: "form-check-input"
        Portfolio item
#   .mb-3
#     .form-check
#       %label.form-check-label
#         = form.check_box :show_on_blog, class: "form-check-input"
#         Blog post
  .mb-3
    .form-check
      %label.form-check-label
        = form.check_box :show_in_calendar, class: "form-check-input"
        Calendar event
  .mb-3
    = form.label :start, class: 'form-label'
    = form.datetime_field :start, class: 'form-control'
  .mb-3
    = form.label :end, class: 'form-label'
    = form.datetime_field :end, class: 'form-control'
  .mb-3
    .form-check
      %label.form-check-label
        = form.check_box :archive, class: "form-check-input"
        Archive
  .mb-3
    - if item.persisted?
      .float-end
        = link_to 'Destroy', item, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' }
    = form.submit class: 'btn btn-primary'
    - if item.persisted?
      = link_to "Cancel", item, class: "btn btn-link"
    - else
      = link_to "Cancel", items_path, class: "btn btn-link"

app/views/items/_item.html.haml
%div{:id => "#{dom_id item}"}
  %p
    %strong Title:
    = item.title
  %p
    %stron Header image:
    = image_tag item.header_image if item.header_image.attached?
  %p
    %strong Description:
    = item.description
  %p
    %strong Content:
    = item.wysiwyg
  %p
    %strong Show on portfolio:
    = item.show_on_portfolio
  # %p
  #   %strong Show on blog:
  #   = item.show_on_blog
  %p
    %strong Show in calendar:
    = item.show_in_calendar
  %p
    %strong Start:
    = item.start
  %p
    %strong End:
    = item.end
  %p
    %strong Archive:
    = item.archive

app/views/items/edit.html.haml
%h1 Edit Item
= render 'form', item: @item

app/views/items/index.html.haml
= search_form_for @q, html: { class: 'form-inline' } do |f|
  .row 
    .col
      = f.search_field :title_cont, class: 'form-control', placeholder: 'Write something here...'
    .col
      = f.submit 'Search', class: 'btn btn-primary'
    .col.text-end
      = link_to new_item_path, class: 'btn btn-primary' do
        +
%br
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Title
        %th Description
        %th Appearance
        %th Start
        %th End
        %th
    %tbody
      - @items.each do |item|
        = content_tag :tr, id: dom_id(item), class: dom_class(item) do
          %td= item.title
          %td= item.description
          %td
            = item.show_on_portfolio
#             = item.show_on_blog
            = item.show_in_calendar
            = item.archive
          %td= item.start
          %td= item.end
          %td= link_to 'Show', item
= will_paginate @items

app/views/items/new.html.haml
%h1 New item
= render 'form', item: @item

app/views/items/show.html.haml
.page-header
  = link_to items_path, class: 'btn btn-default' do
    All Items
  = link_to edit_item_path(@item), class: 'btn btn-primary' do
    Edit
  %h1 Show item
%dl.dl-horizontal
  %dt Title:
  %dd= @item.title
  %dt Header image:
  %dd= image_tag @item.header_image if @item.header_image.attached?
  %dt Description:
  %dd= @item.description
  %dt Content:
  %dd= @item.wysiwyg
  %dt Show on portfolio:
  %dd= @item.show_on_portfolio
#   %dt Show on blog:
#   %dd= @item.show_on_blog
  %dt Show in calendar:
  %dd= @item.show_in_calendar
  %dt Start:
  %dd= @item.start
  %dt End:
  %dd= @item.end
  %dt Archive:
  %dd= @item.archive

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.haml
!!!
%html.h-100
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    = render 'shared/head'
  %body.d-flex.flex-column.h-100
    %main.flex-shrink-0
      = render 'shared/navbar'
      = render 'shared/notices'
      .container.mt-4.mx-auto.p-5
        = yield
    = render 'shared/footer'

app/views/shared/_footer.html.haml
%footer.bg-light.footer.mt-auto.py-3
  .container.d-flex.justify-content-between.mx-auto.text-muted
    %span
      © #{Date.today.year} Bartosz Kulczyk - Made with ❤️ and ☕ but powered by My Crazy Portfolio App
    %ul.d-inline.float-end.list-inline.mb-0
      // %li.list-inline-item.mr-3= link_to "Privacy", privacy_path
      - if user_signed_in?
        %li.list-inline-item.mr-3= link_to "Items", items_path
        %li.list-inline-item.mr-3= link_to "Settings", edit_user_registration_path
        %li.list-inline-item.mr-3= link_to "Logout", destroy_user_session_path, method: :delete
      - else
        %li.list-inline-item.mr-3= link_to "Login", new_user_session_path

app/views/shared/_head.html.haml
%title= Rails.configuration.application_name
%meta{:charset => "utf-8"}/
%meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
= csrf_meta_tags
= csp_meta_tag
%link{:crossorigin => "anonymous", :href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css", :integrity => "sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==", :referrerpolicy => "no-referrer", :rel => "stylesheet"}/
= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload"
= javascript_include_tag "application", "data-turbo-track": "reload", defer: true

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-md.navbar-light.bg-light
  .container.mx-auto
    = link_to Rails.configuration.application_name, root_path, class: "navbar-brand"
    %button.navbar-toggler{"aria-controls" => "navbarsExample04", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarMain", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarMain.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mt-2.mt-md-0
      %ul.navbar-nav
        %li.nav-item= link_to "Portfolio", root_path, class: "nav-link"
        %li.nav-item= link_to "CV", cv_path, class: "nav-link"
        // %li.nav-item= link_to "Blog", blog_path, class: "nav-link"
        %li.nav-item= link_to "Contact", contact_path, class: "nav-link"

app/views/shared/_notices.html.haml
- flash.each do |msg_type, message|
  .container.mt-4.mx-auto
    %div{:class => "alert #{bootstrap_class_for(msg_type)} alert-dismissible fade show", :role => "alert"}
      = message
      %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}